import type { AnchorProfile } from '@/types';

export const DEMO_PROFILES: Record<string, AnchorProfile> = {
  'rahul-sharma': {
    id: 'demo-rahul-sharma',
    user_id: 'demo-user-1',
    name: 'Rahul Sharma',
    slug: 'rahul-sharma',
    tagline: 'Premium Wedding & Corporate Anchor',
    bio: 'Professional anchor & emcee with 8+ years of experience hosting 400+ luxury weddings, corporate summits, and cultural festivals across India and Dubai. Known for high energy, seamless crowd engagement, and impeccable bilingual delivery.',
    city: 'Mumbai',
    state: 'Maharashtra',
    languages: ['Hindi', 'English', 'Marathi'],
    event_types: ['Wedding', 'Sangeet', 'Corporate Event', 'Award Ceremony', 'Concert'],
    profile_photo_url: null,
    cover_photo_url: null,
    phone: '9876543210',
    whatsapp_number: '9876543210',
    email: 'rahul@stagehost.in',
    instagram_url: 'https://instagram.com/anchor_rahul',
    youtube_url: 'https://youtube.com/@anchorrahul',
    facebook_url: 'https://facebook.com/anchorrahulofficial',
    website_url: 'https://rahulsharma.in',
    starting_price: 25000,
    experience_years: 8,
    is_listed_in_directory: true,
    is_profile_complete: true,
    onboarding_step: 4,
    theme_id: null,
    subscription_id: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    videos: [
      {
        id: 'v1',
        profile_id: 'demo-rahul-sharma',
        url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        title: 'Grand Royal Wedding Sangeet Hosting Highlights',
        platform: 'youtube',
        thumbnail_url: 'https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg',
        sort_order: 1,
        created_at: new Date().toISOString(),
      },
      {
        id: 'v2',
        profile_id: 'demo-rahul-sharma',
        url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        title: 'Annual Corporate Tech Summit 2026 MC Reel',
        platform: 'youtube',
        thumbnail_url: 'https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg',
        sort_order: 2,
        created_at: new Date().toISOString(),
      }
    ],
    photos: [],
    service_packages: [
      {
        id: 'sp1',
        profile_id: 'demo-rahul-sharma',
        name: 'The Sangeet & After-Party Experience',
        description: '4 hours of non-stop energy, personalized couple roasts, dance troupe cues, interactive family games, and seamless DJ handoff.',
        event_type: 'Sangeet',
        price_range_min: 55000,
        price_range_max: 75000,
        is_active: true,
        sort_order: 1,
        created_at: new Date().toISOString(),
      },
      {
        id: 'sp2',
        profile_id: 'demo-rahul-sharma',
        name: 'Royal Destination Wedding (Full 2 Days)',
        description: 'Complete coverage for Mehendi, Sangeet Night, Royal Varmala, and Grand Reception. Includes pre-wedding scripting & coordination.',
        event_type: 'Wedding',
        price_range_min: 125000,
        price_range_max: 180000,
        is_active: true,
        sort_order: 2,
        created_at: new Date().toISOString(),
      },
      {
        id: 'sp3',
        profile_id: 'demo-rahul-sharma',
        name: 'Corporate Summit & Annual Gala Emcee',
        description: 'Executive stage presence, CXO panel moderation, formal awards presentation, and bilingual protocol management.',
        event_type: 'Corporate Gala',
        price_range_min: 50000,
        price_range_max: 70000,
        is_active: true,
        sort_order: 3,
        created_at: new Date().toISOString(),
      }
    ],
    testimonials: [
      {
        id: 't1',
        profile_id: 'demo-rahul-sharma',
        client_name: 'Vikram & Ananya Singhania',
        client_designation: 'Couple',
        event_type: 'Destination Wedding, Udaipur',
        text: 'Rahul made our Sangeet night unforgettable! The entire crowd of 400 people was laughing, dancing, and engaged throughout. Best decision we made!',
        rating: 5,
        event_date: '2026-02-14',
        is_visible: true,
        sort_order: 1,
        created_at: new Date().toISOString(),
      },
      {
        id: 't2',
        profile_id: 'demo-rahul-sharma',
        client_name: 'TechCorp India',
        client_designation: 'Head of Events',
        event_type: 'Annual Leadership Summit',
        text: 'Extremely professional, punctual, and adapted smoothly to last-minute schedule changes. Outstanding host!',
        rating: 5,
        event_date: '2026-01-20',
        is_visible: true,
        sort_order: 2,
        created_at: new Date().toISOString(),
      }
    ]
  }
};
